# -*- coding: utf-8 -*-
"""BA1L.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cev69u2ixTtAHL0CAEP6BlGc816Sw01F
"""

def symboltonumber(s):
  if s=="A":
    return 0
  if s=="C":
    return 1
  if s=="G":
    return 2
  if s=="T":
    return 3
  else:
    return "Nije simbol!"

def patterntonumber(pattern):
  if pattern=="":
    return 0
  else:
    simbol=pattern[-1]
    prefix=pattern[0:-1]
    return 4*patterntonumber(prefix) + symboltonumber(simbol)

patterntonumber("TTGTTGGGGTATGCAGAAAAGT")