# -*- coding: utf-8 -*-
"""BA1M.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cev69u2ixTtAHL0CAEP6BlGc816Sw01F
"""

def numbertosymbol(n):
  if n==0:
    return "A"
  if n==1:
    return "C"
  if n==2:
    return "G"
  if n==3:
    return "T"
  else:
    return "Nije trazeni broj!"

def quotient(m,n):
  return m // n

def remainder(m,n):
  return m%n

def concatenation(s,t):
  return s + t

def numbertopattern(index,k):
  if k==1:
    return numbertosymbol(index)
  else:
    prefixindex=quotient(index,4)
    r=remainder(index,4)
    symbol=numbertosymbol(r)
    prefixpattern=numbertopattern(prefixindex, k-1)
    return concatenation(prefixpattern, symbol)

numbertopattern(8909,8)