# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/13BLkuEAhff2iXcvKksgAvrtmkgrXyY-N
"""

def kmer(text, i, k):
    return text[i: i+k]

def hamming(s1, s2):
  d=0
  for i in range(0, len(s1)):
    if s1[i]!=s2[i]:
      d=d+1
  return d

def svi(pattern,dna):
  strings=[]
  rupe=[]
  for i in range(0,len(dna)):
    if dna[i]==" ":
      rupe.append(i)
  k=0
  for j in rupe:
    strings.append(dna[k:j])
    k=j+1
  strings.append(dna[k:])
  t=True
  for string in strings:
    if pattern not in string:
      t=False
  return t

def razlike(pattern,d):
  varijacije=[]
  for i in range(0,len(pattern)-d+1):
    for j in range(0,d):
      var=pattern[0:i] + pattern[i+1:]
      varijacije.append(var)
  return varijacije

razlike("JKSAH",2)

def MotifEnumeration(dna,k,d):
  patterns=set()
  for i in range(0,len(dna)-k+1):
    pattern1=kmer(dna,i,k)
    for j in range(0,len(dna)-k+1):
      pattern2=kmer(dna,j,k)
      if hamming(pattern1,pattern2) <= d :
        if svi(pattern2, dna):
          patterns.add(pattern2)
  return patterns

MotifEnumeration("ATTTGGC TGCCTTA", 3, 1)