# -*- coding: utf-8 -*-
"""BA4D.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ra0ZtuYmVoUqGxoetwRuGIoE4a7gcVoH
"""

def CountingPeptidesWithGivenMass(mass):
    AminoAcidMasses = set([57,71,87,97,99,101,103,113,113,114,115,128,128,129,131,137,147,
            156,163,186])
    counter = dict()
    return CountingAllCombinations(mass,counter,AminoAcidMasses)

def CountingAllCombinations(mass,counter,aa_masses):
    if mass == 0:
        return 1
    if mass < 0:
        return 0
    if mass in counter:
        return counter[mass]
    counter[mass] = 0
    for element in aa_masses:
        counter[mass] += CountingAllCombinations(mass - element,counter,aa_masses)
    return counter[mass]

with open("rosalind_ba4d.txt") as file:
    line = file.readline()
print(CountingPeptidesWithGivenMass(int(line.strip('\n'))))