# -*- coding: utf-8 -*-
"""BA1C.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1svlMEZpdg6QX1qqVBcYcIPfSLcNat9i_
"""

def complement(l):
  if l=="A":
    return "T"
  if l=="T":
    return "A"
  if l=="G":
    return "C"
  if l=="C":
    return "G"

def reverse(pattern):
  r=""
  for i in range (0, len(pattern)):
    r+=complement(pattern[len(pattern) - i - 1])
  return r

reverse("AAAACCCGGT")
