# -*- coding: utf-8 -*-
"""BA1K.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ra0ZtuYmVoUqGxoetwRuGIoE4a7gcVoH
"""

def FillArray(List,t):
    i = 0
    counter = 0 
    
    while (i != len(List)):
            
        if (counter < pow(4,t)):
            List[i] += "A"
        elif ((counter >= pow(4,t)) & (counter < 2*pow(4,t))):
            List[i] += "C"
        elif ((counter >= 2*pow(4,t)) & (counter < 3*pow(4,t))):
            List[i] += "G"
        elif ((counter >= 3*pow(4,t)) & (counter < 4*pow(4,t))):
            List[i] += "T"

        counter += 1
        if counter >= 4*pow(4,t): 
            counter = 0

        i += 1

    return List

def FrequencyArray(Text,k):

    kmers = [""]*pow(4,k)
    frequency =[0]*pow(4,k)
    ispis = ""
    for i in range (k-1,-1,-1):
        kmers = FillArray(kmers,i)
    for i in range (0,len(Text) - k + 1):
        frequency[kmers.index(Text[i:i+k])] += 1

    for element in frequency:
        ispis += str(element) + " "

    return ispis


with open("rosalind_ba1k.txt") as file:
    lines = file.readlines()
print(FrequencyArray(lines[0].strip("\n"),int(lines[1].strip("\n"))))