# -*- coding: utf-8 -*-
"""BA5B.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ra0ZtuYmVoUqGxoetwRuGIoE4a7gcVoH
"""

def ManhattanTourist(n,m,Down,Right):
    matrix=[]
    for i in range (n+1):
        matrix.append([])
    matrix[0].append(0)
    for i in range(1, n+1):
        matrix[i].append(matrix[i-1][0] + int(Down[i-1][0]))
    for j in range(1, m+1):
        matrix[0].append(matrix[0][j-1] + int(Right[0][j-1]))
    for i in range(1,n+1):
        for j in range(1,m+1):
            matrix[i].append(max(matrix[i-1][j] + int(Down[i-1][j]),
                               matrix[i][j-1] + int(Right[i][j-1])))
    return matrix[n][m]

with open("rosalind_ba5b.txt") as file:
    lines = file.readlines()
n = int(lines[0].strip('\n').split(' ')[0])
m = int(lines[0].strip('\n').split(' ')[1])
Down = []
Right = []
for i in range(1,n+1):
    Down.append(lines[i].strip('\n').split(' '))
for i in range(n+2, n+2+n+1):
    Right.append(lines[i].strip('\n').split(' '))
print(ManhattanTourist(n,m,Down,Right))