# -*- coding: utf-8 -*-
"""BA3L.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FFsy0j1HHH_RGUngwa1CXqs3wVGW3vzR
"""

def GappedGenomePath(k,d, pairs):

    # glue all the firsts in pairs
    # they overlap in k-1 places so we only add the last letter of each onto
    # the previous text
    text = pairs[0][0]
    for i in range (1,len(pairs)):
        text += pairs[i][0][-1]
    # the last part of text is a (k+d)- mer that wasn't covered by the
    # firsts in pairs, so we add the second element of the last pair
    # (the last k-mer) and d letters before it
    for i in range(len(pairs) - d - 1, len(pairs) - 1):
        text += pairs[i][1][0]
    text += pairs[-1][1]

    return text


with open("rosalind_ba3l.txt") as file:
    lines = file.readlines()


k = int(lines[0].strip('\n').split(' ')[0])
d = int(lines[0].strip('\n').split(' ')[1])

for i in range (1,len(lines)):
    lines[i] = lines[i].strip("\n").split('|')
    
print(GappedGenomePath(k,d,lines[1:]))