# -*- coding: utf-8 -*-
"""BA6A.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FFsy0j1HHH_RGUngwa1CXqs3wVGW3vzR
"""

def changeSign(number):

    if number[0] == '+':
        number = number.replace('+','-')
    else:
        number = number.replace('-','+')

    return number

'''reversing a segment of permutation'''
def reverse(permutation, start, end):

    rev_segment = []
    segment = permutation[start:(end + 1)]
    new_permutation = []
    
    for i in range(len(segment)-1,-1,-1):

        rev_segment.append(changeSign(segment[i]))

    new_permutation = permutation[:start] + rev_segment + permutation[end+1:]

    return new_permutation

def GreedySorting(P):

    n = len(P)
    permutations = []

    for i in range(1,n+1):

        if P[i-1][1:] != str(i):

            '''reverse the segment between the current position and the position
                of the number that should be in current position'''
            for j in range(i,n):
                if P[j][1:] == str(i):
                    P = reverse(P,i-1,j)
                    permutations.append(P)
                    break

        if P[i-1][0] == '-':
            P = reverse(P,i-1,i-1)
            permutations.append(P)

    return rosalindOutput(permutations)


def rosalindOutput(permutations):

    out = []
    
    for p in permutations:

        line = '(' + ' '.join(p) + ')'
        out.append(line)

    return '\n'.join(out)


with open("rosalind_ba6a.txt") as file:
    line = file.readline()

P = line[1:(len(line)-2)] #excluding ")" and "\n"
P = P.split(' ')

print(GreedySorting(P))